find_package(MatUtils CONFIG REQUIRED)
find_package(cxxopts CONFIG REQUIRED)

add_executable(cgrun cgrun.cpp parser.cpp rhs.cpp)
target_compile_features(cgrun PRIVATE cxx_std_20)
target_include_directories(cgrun PRIVATE ../include)
target_link_libraries(cgrun PRIVATE MatUtils::mat_utils)
target_compile_definitions(cgrun PRIVATE
    $<$<BOOL:${SOLVERS_VERBOSE}>:SOLVERS_VERBOSE>
    $<$<BOOL:${SOLVERS_ENABLE_TIMER}>:ENABLE_TIMER>)

if(SOLVERS_BUILD_CUDA)
    target_sources(cgrun PRIVATE cuda_adapter.cu)
    if(SOLVERS_BUILD_CG)
        target_link_libraries(cgrun PRIVATE cg::cuda)
        target_compile_definitions(cgrun PRIVATE CUDA_CG_ENABLED)
    endif()
    if(SOLVERS_BUILD_DR_BCG)
        target_link_libraries(cgrun PRIVATE dr_bcg::cuda)
        target_compile_definitions(cgrun PRIVATE CUDA_DR_BCG_ENABLED)
    endif()
endif()

if(SOLVERS_BUILD_MKL)
    target_sources(cgrun PRIVATE mkl_adapter.cpp)
    if(SOLVERS_BUILD_CG)
        target_link_libraries(cgrun PRIVATE cg::mkl)
        target_compile_definitions(cgrun PRIVATE MKL_CG_ENABLED)
    endif()
    if(SOLVERS_BUILD_DR_BCG)
        target_link_libraries(cgrun PRIVATE dr_bcg::mkl)
        target_compile_definitions(cgrun PRIVATE MKL_DR_BCG_ENABLED)
    endif()
endif()

include(GNUInstallDirs)
set_target_properties(cgrun PROPERTIES INSTALL_RPATH_USE_LINK_PATH TRUE)
install(TARGETS cgrun RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})